# Use the official Meilisearch image
FROM getmeili/meilisearch:v1.7

# Meilisearch stores data in /meili_data by default
# No need to do anything here unless you want to tweak config

# Optionally expose port (default Meilisearch port)
EXPOSE 7700

# Entrypoint is already defined in the base image to run Meilisearch