name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: cd backend && go mod download

      - name: Run tests
        run: cd backend && go test -v ./...
